---
title: "Materialübersicht und Kursplan"
---

# Einleitung

Das Material ist sortiert nach den drei Präsenztagen. Zu jedem Tag findet ihr Informationen über notwendige Vorbereitungen und Infos zu Nachbereitung. Bitte beachtet, dass es für das Gelingen des Kurses unbedingt erforderlich ist, dass ihr die vorbereitenden Aktivitäten auch durchführt. Sonst funktioniert das Konzept nicht.

Wenn sich zwischen den Terminen Fragen ergeben oder ihr Ideen teilen wollt, nutzt bitte das [Kursforum](https://github.com/graebnerc/EinfuehrungR24/discussions).

# Allgemeine Referenzen

Es gibt eine Reihe von sehr guten und frei verfügbaren R Lehrbüchern, die ich selbst auch immer noch als Nachschlagwerke verwende. Da sich eine Programmiersprache wie R immer mal wieder ein wenig ändert empfehle ich immer Bücher, die online immer wieder geupdated werden.

Besonders empfehlen kann ich hier @r4ds, das eine eher\
datenwissenschaftlich geprägte, sehr praxisnahe Einführung in R darstellt. Es versucht möglichst schnell zu praktischen Anwendungen zu kommen und legt weniger Wert auf die Vermittlung konzeptioneller Grundlagen. Darin unterscheidet es sich ein wenig von dem Fokus dieses Kurses hier.

Ebenfalls sehr empfehlenswert ist @moderndive, das jedoch einen stärkeren Fokus auf die Einführung in die praktische Regressionsanalyse aus einer sozialwissenschaftlichen Perspektive legt. Gerade wenn man in diesem Bereich arbeiten möchte, lohnt es sich hier einen Blick hinein zu werfen.

Wer weiterführende Details zu den Grundlagen der Programmierung in R sucht, dem empfehle ich @advr, das in dieser Hinsicht als Standardwerk gilt und auch eher komplexe Konzepte auf recht anschauliche Art und Weise vermittelt. Es richtet sich aber an Personen, die sich in R schon relativ sicher fühlen und mehr über die zugrundeliegenden Konzepte erfahren wollen.

# Spezifisches Material

Spezifischere Referenzen zu den einzelnen Workshop-Tagen werden auf den jeweiligen Seiten bereit gestellt.

-   [Infos zu Tag 1](Session-01.qmd)
-   [Infos zu Tag 2](Session-02.qmd)
-   [Infos zu Tag 3](Session-03.qmd)
-   [Infos zu Tag 3](Session-04.qmd)

# Kursplan

## Tag 1

| Zeit          | Thema                                                   | Bescheibung                                                                                                                                                                                                                                                                                                        |
|-----------|-----------|-------------------------------------------------|
| 9:00 - 9:30   | Installationsassistenz (optional)                       | Optional, nur für Teilnehmer:innen, die Probleme bei der Installation hatten. Bitte meldet euch vorab per E-Mail oder im [Kursforum](https://github.com/graebnerc/EinfuehrungR24/discussions) ob und ja in welcher Richtung ein Bedarf besteht. Für alle, die keine Probleme hatten beginnt der Kurs erst um 9:45. |
| 9:45 - 10:15  | Block 1.1: Einleitung und Vorstellung                   | Hier stellen sich alle Teilnehmer:innen und ihre Bedarfe vor und das Kursprogramm wird kurz erläutert.                                                                                                                                                                                                             |
| 10:15 - 10:45 | Block 1.2: Grundlagen der Programmiersprache R          | Hier beschäftigen wir uns damit was eine Programmiersprache eigentlich ist, in welcher Hinsicht R besonders ist und was das für die Praxis bedeutet. In diesem Kontext lernen wir auch was es mit Paketen und den unterschiedlichen R Dialekten auf sich hat.                                                      |
| 11:00 - 11:45 | Block 1.3: Projektmanagement für R Projekte             | Wir lernen wie wir ein Forschungsprojekt vorbereiten, welche Ordnerstruktur wir erstellen sollten und wo unsere Daten, Skripte und Outputs gespeichert werden sollten, damit unser Projekt transparent, reproduzierbar und gut zu dokumentieren ist.                                                               |
| 11:45 - 12:00 | Ausblick, Fragen und Erläuterung der Take-Home Aufgaben |                                                                                                                                                                                                                                                                                                                    |
## Tag 2

| Zeit          | Thema                                                   | Bescheibung                                                                                                                                                                                                                                            |
|--------------|--------------|--------------------------------------------|
| 9:00 - 9:30   | Fragen und Übungen                                      | Hier klären wir Fragen zu Übungen zu Tag 1 und vertiefen ggf. Konzepte, mit denen ihr Probleme hattet.                                                                                                                                                 |
| 9:35 - 10:15  | Block 2.1: Einlesen von Daten                           | Anhand von `.csv` Dateien üben wir, wie man mit `data.table::fread()` Daten einzulesen und dabei typische Schwierigkeiten überwinden kann.                                                                                                             |
| 10:30 - 10:45 | Der Analyse-Workflow und das Konzept von 'tidy data'    | Die Arbeit mit empirischen Daten folgt immer einem bestimmten Ablauf. Die einzelnen Schritte klar zu strukturieren hilft in der Praxis die Übersicht zu behalten. Zentral ist dabei die Aufgabe Rohdaten in so genannte 'tidy data' zu transformieren. |
| 10:45 - 11:15 | Block 2.2: Data Wrangling                               | Wir klären Fragen zum Video-Input zum Themenbereich 'data wrangling' und lösen in der Gruppe Übungsaufgaben.                                                                                                                                           |
| 11:30 - 12:00 | Block 2.3.: Data Manipulation                           | Wir klären Fragen zum Video-Input zum Themenbereich 'data manipulation' und lösen in der Gruppe Übungsaufgaben.                                                                                                                                        |
| 12:00 - 12:15 | Ausblick, Fragen und Erläuterung der Take-Home Aufgaben |                                                                                                                                                                                                                               

## Tag 3

## Tag 4

Dieser Termin wird mehrere Wochen nach dem letzten Termin stattfinden und
soll dafür genutzt werden, von den Teilnehmer:innen vorgeschlagene Themen
aufzugreifen und zu vertiefen.
